# Generated by Django 5.2.3 on 2025-07-14 18:21

import django.db.models.deletion
import test_notification.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=100, unique=True)),
                ('branch_contact', models.CharField(help_text='Branch contact number, e.g., +971501234567', max_length=15, null=True)),
                ('location', models.URLField(default='', help_text='Map link (Google Maps, etc.)')),
                ('address', models.TextField(default='Address not provided', help_text='Physical address of the branch')),
                ('radius_of_delivery', models.PositiveIntegerField(default=10, help_text='Delivery radius in kilometers')),
                ('starting_time', models.TimeField(default='09:00:00', help_text='Branch opening time')),
                ('closing_time', models.TimeField(default='17:00:00', help_text='Branch closing time')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('access_level', models.CharField(choices=[('Branch Manager', 'Branch Manager'), ('Staff', 'Staff')], max_length=50)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text="Customer's full name", max_length=100)),
                ('mobile_number', models.CharField(help_text="Customer's mobile number, e.g., +971501234567", max_length=15, unique=True)),
                ('email_address', models.EmailField(blank=True, help_text="Customer's email address", max_length=254, null=True)),
                ('date_of_birth', models.DateField(blank=True, help_text="Customer's date of birth", null=True)),
                ('address', models.CharField(blank=True, help_text="Customer's address", max_length=255, null=True)),
                ('preferred_contact', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('qrmenu', 'QR Menu'), ('voice_call', 'Voice Call')], default='whatsapp', help_text='Preferred contact method', max_length=20)),
                ('total_orders', models.PositiveIntegerField(default=0, help_text='Total number of orders placed')),
                ('total_spent', models.DecimalField(decimal_places=2, default=0.0, help_text='Total amount spent in AED', max_digits=10)),
                ('rating', models.FloatField(blank=True, default=0.0, help_text='Average rating from orders (0-5)', null=True)),
                ('loyalty_points', models.PositiveIntegerField(default=0, help_text='Loyalty points earned')),
                ('action_type', models.CharField(blank=True, choices=[('add_points', 'Add Points'), ('redeem_points', 'Redeem Points')], help_text='Type of action on loyalty points', max_length=20, null=True)),
                ('points_amount', models.PositiveIntegerField(default=0, help_text='Amount of points to add or redeem')),
                ('reason', models.CharField(blank=True, help_text='Reason for points action', max_length=255, null=True)),
                ('delivery_preferences', models.CharField(blank=True, help_text="Customer's delivery preferences", max_length=100, null=True)),
                ('status', models.CharField(default='3rd Tier', help_text='Customer loyalty tier', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LoyaltySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earn_points_per_aed', models.DecimalField(decimal_places=2, default=0.03, help_text='Points earned per 1 AED (e.g., 0.03 means 100 AED = 3 points)', max_digits=5)),
                ('redeem_aed_per_point', models.DecimalField(decimal_places=2, default=0.33, help_text='AED value per point for redemption (e.g., 0.33 means 3 points = 1 AED)', max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last updated timestamp')),
            ],
            options={
                'verbose_name': 'Loyalty Setting',
                'verbose_name_plural': 'Loyalty Settings',
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(help_text='Mobile number to receive notifications (e.g., +971501234567)', max_length=15)),
                ('notification_time', models.TimeField(help_text='Preferred time to receive notifications')),
                ('notification_tune', models.CharField(choices=[('classic', 'Classic'), ('chime', 'Chime'), ('buzz', 'Buzz'), ('silent', 'Silent')], default='classic', help_text='Notification tone to use', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether notifications are enabled for this number')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=10, unique=True)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_phone', models.CharField(blank=True, help_text='Customer phone number, e.g., +971501234567', max_length=15, null=True)),
                ('order_items', models.JSONField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Preparing', 'Preparing'), ('Ready', 'Ready'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('estimated_time', models.PositiveIntegerField(help_text='Estimated time in minutes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('qrcode', 'QR Code'), ('voice_call', 'Voice Call')], default='whatsapp', max_length=20)),
                ('payment_method', models.CharField(blank=True, help_text='Payment method (e.g., Cash, Card, Online)', max_length=50, null=True)),
                ('branch_name', models.CharField(blank=True, help_text='Name of the branch handling the order', max_length=100, null=True)),
                ('customermap', models.CharField(blank=True, help_text='Customer location or map reference (e.g., coordinates or address)', max_length=200, null=True)),
                ('address', models.CharField(blank=True, help_text='Customer delivery address', max_length=200, null=True)),
                ('whatsapp_number', models.CharField(blank=True, help_text='Customer WhatsApp number, e.g., +971501234567', max_length=15, null=True)),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Pending', help_text='Status of the payment', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='OrderChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('qrcode', 'QR Code')], max_length=20)),
                ('orders_count', models.PositiveIntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='PeakHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.TimeField()),
                ('orders_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=2)),
                ('review_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('main_phone_number', models.CharField(max_length=20)),
                ('head_office_address', models.TextField()),
                ('cuisine_type', models.CharField(choices=[('ITALIAN', 'Italian'), ('CHINESE', 'Chinese'), ('MEXICAN', 'Mexican'), ('INDIAN', 'Indian'), ('FRENCH', 'French'), ('JAPANESE', 'Japanese'), ('THAI', 'Thai'), ('AMERICAN', 'American'), ('OTHER', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, storage=test_notification.storage_backends.SupabaseStorage(), upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SalesPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_orders', models.PositiveIntegerField(default=0)),
                ('unique_customers', models.PositiveIntegerField(default=0)),
                ('avg_order_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('revenue_growth', models.DecimalField(decimal_places=2, default=0.0, help_text='Percentage growth vs last period', max_digits=5)),
                ('customer_retention', models.DecimalField(decimal_places=2, default=0.0, help_text='Percentage of returning customers', max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='SMSCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_type', models.CharField(choices=[('PROMOTIONAL', 'Promotional Campaign'), ('ANNOUNCEMENT', 'Announcement'), ('SPECIAL_OFFER', 'Special Offer'), ('EVENT_PROMOTION', 'Event Promotion')], help_text='Type of SMS campaign', max_length=20)),
                ('message_template', models.CharField(choices=[('CUSTOM', 'Custom Message'), ('WELCOME', 'Welcome Message'), ('SPECIAL_OFFER', 'Special Offer'), ('NEW_MENU_LAUNCH', 'New Menu Launch')], help_text='Template for the SMS message', max_length=20)),
                ('selected_customer_data', models.JSONField(help_text="List of customer data in JSON format, e.g., [{'name': 'John', 'mobile_number': '+1234567890'}, ...]")),
                ('message', models.TextField(help_text='The SMS message to be sent to customers')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TopMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('orders_count', models.PositiveIntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('current_stock', models.PositiveIntegerField(default=0)),
                ('min_stock', models.PositiveIntegerField(default=0)),
                ('max_stock', models.PositiveIntegerField(default=0)),
                ('unit', models.CharField(choices=[('kg', 'Kilograms'), ('heads', 'Heads'), ('liters', 'Liters'), ('units', 'Units')], default='units', max_length=20)),
                ('supplier', models.CharField(blank=True, max_length=100)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='test_notification.inventorycategory')),
            ],
        ),
        migrations.CreateModel(
            name='LoyaltyAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('add_points', 'Add Points'), ('redeem_points', 'Redeem Points')], help_text='Type of action on loyalty points', max_length=20)),
                ('points_amount', models.PositiveIntegerField(help_text='Amount of points to add or redeem')),
                ('reason', models.CharField(blank=True, help_text='Reason for points action', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time of adjustment')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_adjustments', to='test_notification.customer')),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, help_text='Discount value (percentage or fixed amount)', max_digits=6, null=True)),
                ('discount_type', models.CharField(blank=True, choices=[('PERCENTAGE', 'Percentage'), ('FIXED', 'Fixed Amount')], help_text='Type of discount: Percentage or Fixed Amount', max_length=20, null=True)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=6, null=True)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, storage=test_notification.storage_backends.SupabaseStorage(), upload_to='')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='test_notification.category')),
                ('tags', models.ManyToManyField(blank=True, to='test_notification.tag')),
            ],
        ),
        migrations.CreateModel(
            name='MenuItemIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_in_grams', models.PositiveIntegerField()),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_notification.ingredient')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='test_notification.menuitem')),
            ],
        ),
    ]
