# Generated by Django 5.2.3 on 2025-07-15 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreference',
            name='notification_duration',
            field=models.PositiveIntegerField(default=5, help_text='Duration (in seconds) to play the notification sound'),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='notification_tune',
            field=models.FileField(blank=True, help_text='Upload a custom notification sound (MP3, WAV, etc.)', null=True, upload_to='notification_sounds/'),
        ),
    ]
