# Generated by Django 5.2.3 on 2025-07-15 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_notification', '0002_notificationpreference_notification_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationpreference',
            name='notification_time',
        ),
    ]
