# Generated by Django 5.2.3 on 2025-07-15 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_notification', '0003_remove_notificationpreference_notification_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationpreference',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when this preference was created'),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when this preference was last updated'),
        ),
    ]
