# Generated by Django 5.2.3 on 2025-07-15 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_notification', '0004_alter_notificationpreference_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Latitude of the branch location', null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Longitude of the branch location', null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='location',
            field=models.URLField(default='', help_text='Map link (Google Maps, etc.)', max_length=300),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Created timestamp'),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Last updated timestamp'),
        ),
    ]
