# Generated by Django 5.2.3 on 2025-07-16 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_notification', '0005_branch_latitude_branch_longitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationpreference',
            name='is_active',
        ),
    ]
