# Generated by Django 5.2.3 on 2025-07-16 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_notification', '0006_remove_notificationpreference_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardholder_name', models.CharField(max_length=100)),
                ('last4', models.CharField(help_text='Last 4 digits of the card number', max_length=4)),
                ('card_type', models.CharField(choices=[('Visa', 'Visa'), ('Mastercard', 'Mastercard'), ('Amex', 'American Express'), ('Other', 'Other')], max_length=20)),
                ('expiry_month', models.IntegerField()),
                ('expiry_year', models.IntegerField()),
                ('card_token', models.CharField(blank=True, help_text='Token from payment gateway', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='test_notification.customer')),
            ],
        ),
    ]
