# Generated by Django 5.2.3 on 2025-07-16 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_notification', '0007_carddetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carddetail',
            name='customer',
        ),
    ]
