# Generated by Django 5.2.3 on 2025-07-16 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_notification', '0008_remove_carddetail_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Branch',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='category',
        ),
        migrations.RemoveField(
            model_name='loyaltyadjustment',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='menuitemingredient',
            name='ingredient',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='category',
        ),
        migrations.DeleteModel(
            name='LoyaltySettings',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='menuitemingredient',
            name='menu_item',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderChannel',
        ),
        migrations.DeleteModel(
            name='PeakHour',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
        migrations.DeleteModel(
            name='Restaurant',
        ),
        migrations.DeleteModel(
            name='SalesPerformance',
        ),
        migrations.DeleteModel(
            name='SMSCampaign',
        ),
        migrations.DeleteModel(
            name='TopMenuItem',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='LoyaltyAdjustment',
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
        migrations.DeleteModel(
            name='InventoryCategory',
        ),
        migrations.DeleteModel(
            name='InventoryItem',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.DeleteModel(
            name='MenuItem',
        ),
        migrations.DeleteModel(
            name='MenuItemIngredient',
        ),
    ]
